using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace alpha
{
    public class PlayerCombat : MonoBehaviour
    {
        // Ref Component
        private PlayerCore m_playerCore;

        public bool IsActionLock => m_isActionLock;
        private bool m_isActionLock;
        // ==================== Swap
        public bool IsSwap { get; private set; }
        public int CurrentSwapNum { get; private set; } = -1;

        public Item CurrentItem;
        public int CurrentWeaponNum { get; private set; } = 0;
        public Action<int, Item> OnSwapAction;

        public WeaponItemDataSO CurrentWeapon;

        public bool IsInCombat => m_isInCombat;
        private bool m_isInCombat;
        public bool IsAttack { get; private set; }
        private float m_nextAttakTime;
        public bool IsAim;
        public bool IsAiming => m_isAiming;
        private bool m_isAiming;
        public bool IsSkill { get; private set; }
        public string SkillKey;

        public bool IsReload { get; private set; }

        public Queue<int> SkillQueue = new Queue<int>();
        public bool IsAction;
        public bool IsActioning;
        private bool m_isAttackDistance;
        public void InitializeModule(PlayerCore playerCore)
        {
            m_playerCore = playerCore;
        }

        public void InitializeEvents(IPlayerEvents events)
        {
            events.CheckInputAction += CheckInput;
        }

        private void Start()
        {
            OnSwapAction += SwapAction;
        }

        private void Update()
        {
            if (CurrentWeapon == null) return;
            //m_isAttackDistance = TryGetTarget(out RaycastHit hit, CurrentWeapon.m_maxDistance);
            SetColorMarkCrossHeadUI(m_isAttackDistance);
        }

        // нҢҢлқјлҜён„° Triggerнҳ•нғңлҠ” KeyDownл°©мӢқмңјлЎң мөңлҢҖн•ң кҙҖлҰ¬
        public void CheckInput()
        {
            // TODO : Locomotionмқҳ мғҒнғңм—җ л”°лҘё Combatмқҳ мһ…л Ҙ boolк°’л“Ө кҙҖлҰ¬

            if (m_playerCore.CombatFlagsController.HasFlag(InputCombatLockType.All))
            {
                IsAttack = false;
                IsSwap = false;
                IsReload = false;
                IsAim = false;
                IsSkill = false;
                return;
            }

            //IsAttack = !m_playerCore.CombatFlagsController.HasFlag(InputCombatLockType.Attack) 
            //&& m_playerCore.InputManager.IsAttack && CurrentWeaponNum > 0;


            /*IsSwap = !m_playerCore.CombatFlagsController.HasFlag(InputCombatLockType.SwapWeapon) 
                    && m_playerCore.InputManager.IsSwap && CanSwapWeapon();*/

            /*IsReload = !m_playerCore.CombatFlagsController.HasFlag(InputCombatLockType.Reload) 
                     && m_playerCore.InputManager.IsReload && CurrentWeaponNum > 1;*/

            IsAim = !m_playerCore.CombatFlagsController.HasFlag(InputCombatLockType.Aim)
                    && m_playerCore.InputManager.IsAim && CurrentWeaponNum > 1;

            IsSkill = !m_playerCore.CombatFlagsController.HasFlag(InputCombatLockType.Skill)
                    & m_playerCore.InputManager.IsSkill && CurrentWeaponNum == 1;
        }

        public void SetActionLock(bool isActionLock)
        {
            m_isActionLock = isActionLock;
        }

        public void SwapAction(int swapNum,Item item)
        {
            CurrentSwapNum = swapNum;
            CurrentItem = item;

            // Swap м• лӢҲл©”мқҙм…ҳ
            m_playerCore.AniController.SwapWeaponAni(swapNum, false);
        }

        public void SetIsAction(bool isAction)
        {
            IsAction = isAction;
        }
        public void SetIKRigWeight(RigType rigType, bool isWeight)
        {
            m_playerCore.IKController.SetRigWeight(rigType, isWeight);
        }
        /// <summary>
        /// мӢӨм ң лҚ°лҜём§ҖлҘј м Ғмҡ©н•ҳлҠ” л©”м„ңл“ң (кұ°лҰ¬ мІҙнҒ¬ нҶөкіј нӣ„ нҳём¶ң)
        /// </summary>
        public void ApplyDamage(RaycastHit hit)
        {
            if (hit.collider.TryGetComponent<HitBox>(out HitBox _hitBox))
            {
                DamageMassage _damageMassage = new DamageMassage();
                //_damageMassage.Damager = damager;
                _damageMassage.HitNormal = hit.normal;
                _damageMassage.HitPoint = hit.point;
                RangeWeaponItemDataSO _range = CurrentWeapon as RangeWeaponItemDataSO;
                //_damageMassage.Damage = _range.WeaponData.CombatData.Damage;

                _hitBox.damageable.ApplyDamage(_damageMassage);
                print("нһҲнҠёл°•мҠӨ лҚ°лҜём§Җ мҷ„лЈҢ");

            }
            // TODO: н”јкІ© мқҙнҺҷнҠё мһ¬мғқ л“ұ

        }

        #region ================================================ Enter, Exit State
        public void EnterInCombat()
        {
            m_isInCombat = true;
            m_playerCore.AniController.SetIsInCombatAni(m_isInCombat);
        }

        public void ExitInCombat(bool isFlying)
        {
            m_isInCombat = false;
            IsActioning = false;

            m_playerCore.AniController.SetIsInCombatAni(false);

            if (!isFlying)
                m_playerCore.AniController.SetAnimatorWeight(1, 0);

            m_playerCore.AniController.SetAnimatorWeight(2, 0);
            m_playerCore.AniController.SetAnimatorWeight(3, 0);
        }

        public void Attack()
        {
            MeleeWeaponItemDataSO _meleeWeapon = null;
            RangeWeaponItemDataSO _rangeWeapon = null;

            if (CurrentWeaponNum == 1)
            {
                m_playerCore.AniController.SetAnimatorWeight(2, 1);
                SetIKRigWeight(RigType.Aim, false);
                _meleeWeapon = CurrentWeapon as MeleeWeaponItemDataSO;

                if (!IsActioning)
                {
                    //_meleeWeapon.Attack(IsAttack, m_playerCore.AniController);
                }
            }
            else if (CurrentWeaponNum > 1)
            {
                SetIKRigWeight(RigType.Aim, true);
                _rangeWeapon = CurrentWeapon as RangeWeaponItemDataSO;
                //RealTimeUIManager.Instance.SetAmmo(_rangeWeapon.CurrentAmmo, _rangeWeapon.SaveAmmo, _rangeWeapon.MaxAmmo);
                m_playerCore.AniController.SetAnimatorWeight(1, 1);
                if (Time.time >= m_nextAttakTime)
                {
                    //m_nextAttakTime = Time.time + _rangeWeapon.WeaponData.CombatData.Cooldown;
                    // л¬ҙкё° SwapмӢң л§ҲлӢӨ мҠӨлӮҳмқҙнҚј к°ҷмқҖ мҙқмқҳ кІҪмҡ° л°”лЎң л°ңмӮ¬лҘј н•ҳл©ҙ м•Ҳлҗҳкё°м—җ кі„мҶҚ нҳ„мһ¬ л¬ҙкё°к°’мңјлЎң
                    //_rangeWeapon.Attack(IsAttack, m_playerCore.AniController);
                    //if (TryGetTarget(out RaycastHit hit, CurrentWeapon.m_maxDistance))
                    {
                        //ApplyDamage(hit);
                    }
                }
            }
        }
        /// <summary>
        /// кұ°лҰ¬ лӮҙ л§һмқҖ лҢҖмғҒмқҙ мһҲлҠ”м§Җ нҷ•мқё (лӢЁмҲң мІҙнҒ¬мҡ©)
        /// </summary>
        public bool TryGetTarget(out RaycastHit hit, float maxDistance)
        {
            Vector3 origin = Camera.main.transform.position;
            Vector3 dir = Camera.main.transform.forward;

            bool isHit = Physics.Raycast(origin, dir, out hit, maxDistance, 1 << LayerMask.NameToLayer("Enemy"));

            return isHit;
        }

        public void SetColorMarkCrossHeadUI(bool isDistance)
        {
            RealTimeUIManager.Instance.SetColorMarkCrossHead(isDistance);
        }
        /// <summary>
        /// PlayerмҳӨлёҢм қнҠё н•ҳмң„м—җ мһҲлҠ” к°Ғ Holder мҳӨлёҢм қнҠё On/Off л°©мӢқ
        /// TODO мҠӨмҷ‘мӢң мҠӨмҷ‘мғҒнғңм—җм„ң мӢңк°„м—җ мқҳн•ҙ м• лӢҲл©”мқҙм…ҳ Numк°’кіј мӢӨм ң Swapк°’мқҙ лӢӨлҘҙкІҢ к°Җ~лҒ”лӮҳмҳҙ н•ҙкІ°н•„мҡ”
        /// </summary>


        public void EnterSwapWeapon(bool isFlying)
        {
            m_playerCore.AniController.SetAnimatorWeight(1, 1);
            m_playerCore.AniController.SwapWeaponAni(CurrentWeaponNum, isFlying);

            if (CurrentWeaponNum > 1)
            {
                //RangeWeaponItemDataSO _rangeWeapon = CurrentWeapon as RangeWeaponItemDataSO;
                // RealTimeUIManager.Instance.SetAmmo(_rangeWeapon.CurrentAmmo, _rangeWeapon.SaveAmmo, _rangeWeapon.MaxAmmo);
            }
            else RealTimeUIManager.Instance.SetAmmo(0, 0, 0);
        }
        public void SwapInventoryWeapon()
        {
            //OnSwapAction?.Invoke(CurrentWeaponNum);
        }

        public void ExitSwapWeapon(bool isFlying)
        {
            if (CurrentWeaponNum > 1)
            {
                RangeWeaponItemDataSO _rangeWeapon = CurrentWeapon as RangeWeaponItemDataSO;
                //RealTimeUIManager.Instance.SetAmmo(_rangeWeapon.CurrentAmmo, _rangeWeapon.SaveAmmo, _rangeWeapon.MaxAmmo);
            }
            else RealTimeUIManager.Instance.SetAmmo(0, 0, 0);

            if (!isFlying)
                m_playerCore.AniController.SetAnimatorWeight(1, 0);
        }

        // TODO : м •лҰ¬ нӣ„ кі л Ө
        /*public void AttackRootMotion(bool isApplyRoot)
        {
           // m_animationController.SetApplyRootMotion(isApplyRoot);
        }*/

        public void SetAming(bool isOffAiming = false)
        {
            m_isAiming = !m_isAiming;
            if (isOffAiming) m_isAiming = false;

            RealTimeUIManager.Instance.ChangeSniperAimUI(m_isAiming ? (CurrentWeaponNum == 3 ? true : false) : false);
            m_playerCore.CameraManger.AimFOV(m_isAiming, CurrentWeaponNum == 3);
        }

        public bool EnterReload()
        {
            RangeWeaponItemDataSO _rangeWeapon = CurrentWeapon as RangeWeaponItemDataSO;
            //bool _cansReload = _rangeWeapon.Reload();
            bool _cansReload = false;
            if (!_cansReload) return false;

            //RealTimeUIManager.Instance.SetAmmo(_rangeWeapon.CurrentAmmo, _rangeWeapon.SaveAmmo, _rangeWeapon.MaxAmmo);

            m_playerCore.AniController.SetAnimatorWeight(1, 1);
            m_playerCore.AniController.ReloadAni();

            //m_playerCore.AudioManager.PlaySFXCombatAudio(SFX_CombatType.Reload);
            return true;
        }
        public void ExitReload(bool isFlying)
        {
            if (!isFlying)
                m_playerCore.AniController.SetAnimatorWeight(1, 0);
        }

        public void EnterSkill()
        {
            SkillKey = m_playerCore.InputManager.SkillKey;
            m_playerCore.AniController.SkillAni(SkillKey);
            m_playerCore.AniController.SetAnimatorWeight(2, 1);
        }
        public void ExitSkill()
        {
            m_playerCore.AniController.SetAnimatorWeight(2, 0);
        }
        #endregion ================================================ /Enter,Exit State
    }
}
